### ISSUE TITLE
Modification of importAdventure hook

### ISSUE THREAD

**Issue by LeRatierBretonnien** [pafvel/dragonbane#79]
With the current importAdventure hook code, the next importAdventure hooks function are never called. It seems a Foundry bug, but to avoid this behavior, here is the modification for the hook in your system : 
```js
// Re-generate thumbnails when importing scenes
Hooks.on('importAdventure', async (created, _updated) => {
    if (created?.scenes?.size > 0) {
        console.log("Dragonbane: Re-generating thumbnails for " + created.name);
        setTimeout( async () => {
          created.scenes.forEach(async s => {
            const scene = game.scenes.get(s.id);
            const thumb = await scene.createThumbnail();
            scene.update({ "thumb": thumb.thumb });
        })
      }, 200);
    }
});
```

**Comment by pafvel** [comment]
I can not reproduce your problem. There is another importAdventure hook in the system that is always called after this one. Moreover, there is as far as I can tell, no way for the code that calls the hooks to skip a hook. Are you sure it is never called?

I noticed that due to the async nature of the calls the hooks may be executed in parallel and that for example console.log() calls may end up nested inside the console logging for thumbnails. As far as I can tell, I can not prevent parallel execution of the hooks but maybe I'm missing something...

I plan to bake the thumbnails into the module and skip thumbnail re-generation if the thumbnail exists. This should make this less of an issue in the future..

If you are certain that your hook is not being called, please provide some code I can use to reproduce.

**Comment by LeRatierBretonnien** [comment]
According to the Foundry team (cf their Discord), foreach is known to induce weird issues with Hooks function. Right now, in the module, I am disabling the Dragonbane system hook in the global hooks table, and recreating it with the code above. This is the only solution I found to make it working.

**Comment by pafvel** [comment]
The new system version from a few days ago no longer uses foreach, so if you still have problems then that's not why.

I have no idea what your module is doing, so I can't help further unless you provide code that I can use to reproduce the behavior you're seeing.
